### PR TITLE
Add ghc 8.0.1 to travis

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
@tibbe, btw. I bumped a base upper bound for latest hashable release on Hackage: http://matrix.hackage.haskell.org/package/hashable

Also unordered-contaienrs http://matrix.hackage.haskell.org/package/unordered-containers are all green

**Comment by phadej** [comment]
The hackage edit is reverted: https://github.com/ekmett/semigroups/issues/56

I'll make a PR with instances tomorrow

**Comment by tibbe** [comment]
Thank you!

**Comment by phadej** [comment]
Actually @hvr made https://github.com/tibbe/hashable/pull/111 which got into 1.2.4.0, so it's actually ready for GHC 8.0. So no more worries with this package.

**Pull request merged**
